config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  devise_scope :user do

    authenticated :user do
      root 'patient#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end

  end

  root 'dashboard#index', as: :root

  resources :patient do
    resources :documents
  end


  get 'import/patient', to: 'import#import_patient'
  post 'save/patient', to: 'import#save_patient'
  get 'export/patient', to: 'export#create_file'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord


  validates_presence_of :first_name, :last_name, :email, :mrn
  validates_format_of :email,:with => Devise::email_regexp

  has_many_attached :documents

  searchable do
    text :full_name
    text :mrn
    string :full_name
    string :is_insured do
      is_insured ? 'yes' : 'no'
    end
  end


  def full_name
    "#{first_name} #{last_name}"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :rememberable, :validatable,:omniauthable, :omniauth_providers => [:google_oauth2]

  validates_confirmation_of :password, :if => :password_required?

  def self.from_google(email:, full_name:, uid:, provider:)
    where(provider: provider, uid: uid).first_or_create do |user|
       user.provider = provider
       user.uid = uid
       user.email = email
       user.full_name = full_name
    end
  end



  def password_required?
    super && provider.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery
  before_action :authenticate_user!

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :patient
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def new
    @document = @patient.documents.build
  end

  def index
    @documents = @patient.documents
  end

  def create
    if @patient.documents.attach(document_params[:documents])
      flash[:notice] = 'Medical records was successfully created'
      redirect_to patient_documents_path(@patient.id)
    else
      flash[:alert] = 'Medical records was not created successfully'
      redirect_back(fallback_location: authenticated_root_path)
    end
  end

  def destroy
    if @patient.documents.find(params[:id]).purge
      flash[:notice] = 'Medical records was successfully deleted'
    else
      flash[:alert] = 'Medical records was not deleted successfully'
    end
    redirect_back(fallback_location: authenticated_root_path)
  end

  private

  def document_params
    params.require(:attachment).permit(documents: [])
  end

  def patient
    @patient = Patient.find(params[:patient_id])
  end

  def record_not_found
    flash[:alert] = "Wrong Patient ID"
    redirect_back(fallback_location: authenticated_root_path)
  end

end

app/controllers/export_controller.rb
class ExportController < ApplicationController

  before_action :export_service, only: [:create_file]

 def create_file
   file = @export_service.export_data(export_params)
   send_file file, :disposition => 'attachmnet'
 end

  private

  def export_params
    params.permit(:sort_by, :order, :term, :is_insured, :file_format)
  end

  def export_service
    @export_service = ImportExportService.new
  end

end

app/controllers/import_controller.rb
class ImportController < ApplicationController

  before_action :import_service, :only=> :save_patient

  def import_patient
    @patient = Patient.new
  end

  def save_patient
    columns,values = @import_data_service.import_data(params[:import][:file])
    patients = Patient.import columns, values, validate: true, validate_uniqueness: true, track_validation_failures: true
    Patient.reindex
    flash[:notice] = "#{patients.ids.count} Patients were successfully created"
    redirect_to patient_index_path
  end

  private

  def import_params
    params.require(:import).permit(:file)
  end

  def import_service
    @import_data_service = ImportExportService.new
  end

end

app/controllers/patient_controller.rb
class PatientController < ApplicationController

  before_action :page,:search_service, only: [:index]
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

 LIMIT = 10

  def new
    @patient = Patient.new
  end

  def index
    @patients, @total_patients ,@total_pages = @search_service.search(search_params, LIMIT)
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      flash[:notice] = 'Patient was successfully created'
      redirect_to patient_path(@patient.id)
    else
      flash[:alert] = 'Patient was not created successfully'
      redirect_back(fallback_location: authenticated_root_path)
    end
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    patient = @patient.update(patient_params)
    if patient
      flash[:notice] = 'Patient was successfully updated'
      redirect_to patient_path(@patient.id)
    else
      flash[:alert] = 'Patient was not updated successfully'
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    if @patient.destroy
      flash[:notice] = 'Patient was successfully deleted'
    else
      flash[:alert] = 'Patient was not deleted successfully'
    end
    redirect_back(fallback_location: authenticated_root_path)
  end


  private

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :email, :zip, :mrn, :dob, :mobile_number, :is_insured, documents: [])
  end

  def search_params
    params.permit(:sort_by, :order, :term, :is_insured, :page)
  end

  def page
    @page = search_params[:page].present? ? params[:page].to_i : 1
  end

  def search_service
    @search_service = SearchService.new
  end

  def record_not_found
    flash[:alert] = "Wrong Patient ID"
    redirect_back(fallback_location: authenticated_root_path)
  end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    user = User.from_google(from_google_params)

    if user.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect user, event: :authentication
    else
      debugger
      flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end
  end

  protected

  def after_omniauth_failure_path_for(_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end

  private

  def from_google_params
    @from_google_params ||= {
        uid: auth.uid,
        email: auth.info.email,
        full_name: auth.info.name,
        provider: auth.provider,

    }
  end

  def auth
    @auth ||= request.env['omniauth.auth']
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def asc_sort_link(params={})
    link_to "&uarr;".html_safe, patient_index_path(params.except(:controller,:action).to_unsafe_h)
  end
  def desc_sort_link(params={})
    link_to "&darr;".html_safe, patient_index_path(params.except(:controller,:action).to_unsafe_h)
  end

end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/export_helper.rb
module ExportHelper
end

app/helpers/import_helper.rb
module ImportHelper
end

app/helpers/patient_helper.rb
module PatientHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-light bg-light mb-3">
    <a class="navbar-brand" href=""><span class="logo-one">Patient</span> <span class="logo-two">Registry</span></a>
  <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  <% else %>
      <%= link_to('Login', new_user_session_path) %>
  <% end %>
</nav>

app/views/documents/_list.html.erb
<% documnets.each do |document| %>
    <tr>
      <td><%= document.filename %></td>
      <td><%= document.created_at %></td>
      <td><%= link_to ' Destroy', patient_document_path(patient,document), data: {:confirm => 'Are you sure?'}, :method => :delete %> |
        <%= link_to 'Download', rails_blob_path(document, disposition: "attachment") %>
      </td>

    </tr>
<% end %>

app/views/documents/index.html.erb
<div class="row mt-3">
  <div class="col-12">
    <div class="row">
      <div class="col-12 mb-3">
        <%= link_to "Add new record", new_patient_document_path(@patient), class:'btn btn-primary float-right ml-2' %>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <table class="table table-bordered patient-list mt-3">
          <thead>
          <tr>
            <th>Name</th>
            <th>Cretaed at</th>
            <th>Action</th>
          </tr>
          </thead>
          <tbody id="patient-records">
          <% if @documents %>
              <%= render "list", documnets: @documents, patient: @patient %>
          <% end %>
          </tbody>
        </table>

      </div>

    </div>

  </div>
</div>

app/views/documents/new.html.erb
<%= form_for @document, as: :attachment, url: patient_documents_path(@patient), method: 'post', html: { class: "", id: "" } do |f| %>
    <div class="form-group">
      <label for="document">Medical records document</label>
      <%= f.file_field :documents, multiple: true, class: 'form-control-file'%>
    </div>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/import/import_patient.html.erb
<div class="row">
  <div class="col-12">
    <a href="/template/patient.csv" target="_blank">CSV Template</a> |
    <a href="/template/patient.xml" target="_blank">XML Template</a> |
    <a href="/template/patient.json" target="_blank">JSON Template</a>
  </div>
  <div class="col-12">
    <a href="/sample/patient.csv" target="_blank">CSV Sample</a> |
    <a href="/sample/patient.xml" target="_blank">XML Sample</a> |
    <a href="/sample/patient.json" target="_blank">JSON Sample</a>
  </div>
</div>

<%= form_for @patient, as: :import, url: '/save/patient', method: 'post', html: { class: "", id: "" } do |f| %>
    <div class="form-group">
  <%= f.label :file, "Upload File" %>
  <%= f.file_field :file, class: 'form-control-file', required: true %>
</div>
<%= button_tag do %>
    <i class='icon-white icon-ok'></i> Upload File
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PatientRegistry</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render 'navbar' %>
  <div class="container-fluid">

    <div class="row text-center">
    <% if notice %>
      <div class="alert alert-success notice alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    </div>
    <%= yield %>
  </div>


  </body>
</html>

app/views/patient/_export_form.html.erb
<%= form_tag(export_patient_path,method: :get, class: 'form-inline float-right')  do %>
    <div class="form-group mx-sm-3">
      <%= select_tag 'file_format', options_for_select([['CSV', 'csv'],['JSON', 'json'],['XML', 'xml']], params[:file_format]) , class: 'form-control' %>
    </div>
    <%= hidden_field_tag :term, params[:term] %>
    <%= hidden_field_tag :is_insured, params[:is_insured] %>
    <%= hidden_field_tag :sort_by, params[:sort_by] %>
    <%= hidden_field_tag :order, params[:order] %>
    <div class="form-group">
      <%= submit_tag 'Export',name: nil, class: 'btn btn-info' %>
    </div>
<% end %>

app/views/patient/_form.html.erb
<div class="form-group">
  <label for="first_name">First Name</label>
  <%= f.text_field :first_name, value: f.object.first_name, autofocus: true,autocomplete: false, required: '',maxlength: "50", class: 'form-control'%>
</div>

<div class="form-group">
  <label for="last_name">Last Name</label>
  <%= f.text_field :last_name, value: f.object.last_name, autocomplete: false, required: '',maxlength: "50", class: 'form-control'%>
</div>

<div class="form-group">
  <label for="email">Email</label>
  <%= f.email_field :email,value: f.object.email, autocomplete: false, required: '',maxlength: "50", class: 'form-control'%>
</div>

<div class="form-group">
  <label for="mrn">Medical Record Number</label>
  <%= f.text_field :mrn, value: f.object.mrn, autocomplete: false, maxlength: "12",pattern: "[0-9]+", placeholder: '1234567678', class: 'form-control'%>
</div>

<div class="form-group">
  <label for="mrn">Zip</label>
  <%= f.text_field :zip,value: f.object.zip, autocomplete: false, placeholder:'12345', maxlength: "5",minlength: "5", class: 'form-control'%>
</div>

<div class="form-group">
  <label for="dob">Date of Birth</label>
  <%= f.date_field :dob, value: f.object.dob.try(:strftime,"%Y-%m-%d"), autocomplete: false, class: 'form-control'%>
</div>

<div class="form-group">
  <label for="mobile_number">Mobile number</label>
  <%= f.text_field :mobile_number, autocomplete: false, required: '', maxlength: "12", pattern: "[0-9]+",placeholder: '1234567678', class: 'form-control'%>
</div>
<div class="form-group">
  <label for="mrn">Is insured?</label>
  <div class="form-check">
    <%= f.radio_button :is_insured, true %>
    <label class="form-check-label" for="is_insured_yes">
      Yes
    </label>
  </div>
  <div class="form-check">
    <%= f.radio_button :is_insured, false %>
    <label class="form-check-label" for="is_insured_no">
      No
    </label>
  </div>
</div>
<div class="form-group">
  <label for="document">Medical records document</label>
  <%= f.file_field :documents, multiple: true, class: 'form-control-file.'%>
</div>
<div class="form-group">
  <%= f.submit "Save", class: 'btn btn-primary btn-lg btn-block' %>
</div>

app/views/patient/_list.html.erb
<tr class="hidden page-number" data-page="<%= page %>"></tr>
<% patients.each do |patient| %>
<tr>
  <td><%= patient.full_name %></td>
  <td><%= patient.email %></td>
  <td><%= patient.mobile_number %></td>
  <td><%= patient.mrn %></td>
  <td><%= patient.is_insured ? 'Yes' : 'No' %></td>
  <td><a href="patient/<%= patient.id %>/edit" class="link">Edit</a> | <a href="<%= patient_documents_path(patient) %>" >Documents</a> |<%= link_to ' Destroy', patient_path(patient),
                                                                                  data: {:confirm => 'Are you sure?'}, :method => :delete %>  </td>

</tr>
<% end %>

app/views/patient/_search_form.html.erb
<%= form_tag(patient_index_path,method: :get, class: 'form-inline')  do %>
    <div class="form-group">
      <%= text_field_tag :term, params[:term], placeholder: 'Seach name, mrn, mobile number', class: 'form-control' %>
    </div>
    <div class="form-group mx-sm-3">
      <label class="pr-2">Is Insured? </label>
      <%= select_tag 'is_insured', options_for_select([['Yes', 'yes'],['No','no']], params[:is_insured]) , prompt: "Select", class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= submit_tag 'Search',name: nil, class: 'btn btn-info' %>
    </div>
<% end %>

app/views/patient/edit.html.erb
<div class="row">
  <div class="col-xl-4 offset-xl-4 col-sm-12">
    <h2>Sign up</h2>

    <%= form_for @patient, as: :patient, url: "/patient/#{@patient.id}", method: 'PUT', html: { class: "", id: "" } do |f| %>
        <%= render "form", f: f %>
    <% end %>

  </div>
</div>

app/views/patient/index.html.erb
<div class="row mt-3">
  <div class="col-12">
    <div class="row">
      <div class="col-12 mb-3">
        <%= render "export_form" %>
        <%= link_to "Import", import_patient_path, class:'btn btn-primary float-right ml-2' %>
        <%= link_to "Create", new_patient_path, class:'btn btn-primary float-right ' %>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <%= render "search_form" %>
        <table class="table table-bordered patient-list mt-3" data-total-patients="<%= @total_patients %>" data-total-pages="<%= @total_pages %>">
          <thead>
          <tr>
            <th >Full Name <%= asc_sort_link(params.merge({order: 'asc', sort_by: 'full_name'})) %>
              <%= desc_sort_link(params.merge({order: 'desc', sort_by: 'full_name'})) %> 	</th>
            <th>Email</th>
            <th>Mobile Number</th>
            <th>MRN</th>
            <th>Is Insured <%= asc_sort_link(params.merge({order: 'asc', sort_by: 'is_insured'})) %>
              <%= desc_sort_link(params.merge({order: 'desc', sort_by: 'is_insured'})) %></th>
            <th>Action</th>
          </tr>
          </thead>
          <tbody id="patient-records">
            <% if @patients %>
              <%= render "list", patients: @patients, page: @page %>
            <% end %>
          </tbody>
        </table>

      </div>

    </div>

  </div>
</div>


<div id="pagination"></div>

<script>
  $(document).ready(function(){
      var pageList = $('.patient-list')
      $('#pagination').bootstrapPaginator({
          currentPage: $('.page-number').data('page'),
          totalPages: pageList.data('total-pages'),
          alignment: 'right',
          pageUrl: function(type, page, current){
              var currentUrl = window.location.href;
              var url = new URL(currentUrl);
              url.searchParams.set("page", page); // setting your param
              return url.href;
          }
          });

  })
</script>

app/views/patient/new.html.erb
<div class="row">
  <div class="col-xl-4 offset-xl-4 col-sm-12">
    <h2>Sign up</h2>

    <%= form_for @patient, as: :patient, url: '/patient', method: 'post', html: { class: "", id: "" } do |f| %>
        <%= render "form", f: f %>

    <% end %>

  </div>
</div>

app/views/patient/show.html.erb
<div class="row">
  <div class="col-xl-6 offset-xl-3 col-sm-12">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td>First Name</td>
          <td><%= @patient.first_name %></td>
        </tr>
        <tr>
          <td>Last Name</td>
          <td><%= @patient.last_name %></td>
        </tr>
        <tr>
          <td>Email</td>
          <td><%= @patient.email %></td>
        </tr>
        <tr>
          <td>Medical Record Number</td>
          <td><%= @patient.mrn %></td>
        </tr>
        <tr>
          <td>Zip</td>
          <td><%= @patient.zip %></td>
        </tr>
        <tr>
          <td>Mobile Number</td>
          <td><%= @patient.mobile_number %></td>
        </tr>
        <tr>
          <td>Is Insured</td>
          <td><%= @patient.is_insured ? 'Yes' : 'No' %></td>
        </tr>
      </tbody>
    </table>
    <div class="form-group">
      <a href="<%= edit_patient_path(@patient) %>" class='btn btn-primary'>Edit Patient Records</a>
      <a href="<%= patient_documents_path(@patient) %>" class='btn btn-primary'>Edit Patient Documents</a>
    </div>
  </div>
</div>